#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

function main {
    mkdir -p "${XDG_CONFIG_HOME}/ssh"

    ln -sf "${CURRENT_DIR}/config" "${XDG_CONFIG_HOME}/ssh/config"
}

main
