#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

function main {
    sh -c "$(curl -fsSL \
        "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/\
        install.sh")" -- --unattended
    rm -rf "${XDG_CONFIG_HOME}/zsh/.zshrc"
    ln -sf "${CURRENT_DIR}/.zprofile" "${XDG_CONFIG_HOME}/zsh/.zprofile"
    ln -sf "${CURRENT_DIR}/.zshenv" "${XDG_CONFIG_HOME}/zsh/.zshenv"
    ln -sf "${CURRENT_DIR}/.zshrc" "${XDG_CONFIG_HOME}/zsh/.zshrc"
    ln -sf "${CURRENT_DIR}/aliases.zsh" \
        "${XDG_CONFIG_HOME}/zsh/ohmyzsh/custom/aliases.zsh"
    ln -sf "${XDG_CONFIG_HOME}/zsh/.zshenv" \
        "${HOME}/.zshenv" # required for the zsh bootstrapping problem
}

main
